### ISSUE TITLE
Document paid app receipt checking

### ISSUE THREAD

**Issue by kumar303** [mozilla/fxpay#111]
The fxpay app receipt validation features need to be documented here: https://developer.mozilla.org/en-US/Marketplace/Monetization/In-app_payments_section/fxPay_iap

**Comment by chrisdavidmills** [comment]
And the adapter too, as mentioned on https://bugzilla.mozilla.org/show_bug.cgi?id=1123791?

I'm happy to add material to cover this, if you can provide me with some rough notes on how they work to write up.

**Comment by kumar303** [comment]
I think the adapter is less important than documenting receipt validation with ``fxpay``. The best way to see how validation works is to check out the [example](https://github.com/mozilla/fxpay/blob/master/example/hosted-paid-app/media/js/index.js#L43). This shows how a developer of a paid app could use fxpay to check the receipt.

Some notes:
* You can ignore the ``receiptCheckSites`` configuration which whitelists pre-production servers. Developers will not need to do this. They can use the prod server for everything, even testing.
* The ``allowTestReceipts`` option is a useful configuration option for developers. Here is a [page](https://developer.mozilla.org/en-US/Marketplace/Monetization/Validating_a_receipt#Test_receipts) explaining how a developer can use test receipts to test that their code is validating receipts correctly. They should turn this off for production because otherwise people can use their app for free with test receipts.
* If you want to run the example app, the [installation instructions](https://github.com/mozilla/fxpay/tree/master/example/hosted-paid-app) should hopefully work.
* The [product info](https://developer.mozilla.org/en-US/Marketplace/Monetization/In-app_payments_section/fxPay_iap#Product_Info_Object) object should be fully documented.

**Comment by chrisdavidmills** [comment]
So a couple of followup questions:

1. This section seems to talk about receipt validation too, but using a different method: https://developer.mozilla.org/en-US/Marketplace/Monetization/In-app_payments_section/fxPay_iap#Restoring_Products_From_Receipt. Is this out of date info, or is it talking about a slightly different context?

2. You talk about fully documenting the product info object - is the existing material out of date, or do you just want it documented as a proper API object, in the same fashion as say https://developer.mozilla.org/en-US/docs/Web/API/Headers ? Is there a spec available that I can work from?

**Comment by kumar303** [comment]
The existing in-app receipt validation is up to date. It's confusing but there are indeed two types of receipt validation: 

1. If you sell your app as paid then when your app starts up, it will need to validate its receipt. 
2. Completely unrelated and separate from that, an app may choose to sell in-app products. When a user purchases an in-app product, a receipt gets installed on device *per product*. When the app starts up, it needs to check for those in-app product receipts so it can know to restore the purchased products. 

Let me know if you still have questions about that.

If you want to fix up the formatting of the product info docs then go for it -- yeah, the Headers docs you linked to are easier to read and skim through. What I meant earlier was that the current docs are up to date. It's just a plain JavaScript object. There isn't really a spec. You could sort of look at [this code here](https://github.com/mozilla/fxpay/blob/master/lib/fxpay/products.js#L123) but there could be some private attributes that we don't need to document. For example, ``getReceiptMap`` is unnecessary to document for end users.

**Comment by chrisdavidmills** [comment]
I have added the following section to the fxpay article:

https://developer.mozilla.org/en-US/Marketplace/Monetization/In-app_payments_section/fxPay_iap#Validating_an_app_receipt

I have also updated these relevant sections with mentions and links:

https://developer.mozilla.org/en-US/Marketplace/Monetization/App_payments_guide#Verify_the_receipt
https://developer.mozilla.org/en-US/Marketplace/Monetization/Validating_a_receipt#How_to_validate_a_receipt

I see what you mean now for the product info object. I think I'll not put it on its own page, as it is a JS library object, not a browser API. However, I have rearranged the article slightly, to put all the reference stuff in its own section:

https://developer.mozilla.org/en-US/Marketplace/Monetization/In-app_payments_section/fxPay_iap#fxpay_reference

and cut out some of the other headings in the  TOC that were making it feel cluttered. Let me know if that is any easier to parse, and if you think it needs anything else.

**Comment by kumar303** [comment]
Great, thanks! I'll close this out. I just made a few tweaks:

* there was a bit of a narrative going in the order of fetching in-app products then validating in-app receipts so I just moved the paid app validation section underneath that
* I removed the irrelevant (and undefined) functions from the code sample since those were only specific to the example app
