### ISSUE TITLE
Use releases instead of the changelog in the README

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/fxpay#69]
We could use the releases feature on github instead of the changelog in the readme, it's a bit nicer for tying changes to the tags.

**Comment by kumar303** [comment]
will that have a lot of noise in the list of commits though? What's nice about the changelog is that someone who is upgrading the library can glance at the notes and easily see any backwards incompatible changes. I'd be worried that using the git log would show a lot of merge commits and bump this / bump that type of messages.

**Comment by muffinresearch** [comment]
I don't think that does anything to the tree. See  https://github.com/mozilla/marketplace-core-modules/releases

**Comment by kumar303** [comment]
oh, cool. So we can add arbitrary notes that show up on the releases page? https://github.com/mozilla/fxpay/releases That sounds like a good alternative to maintaining it in the readme.

**Comment by muffinresearch** [comment]
This is done. Closing.
