### ISSUE TITLE
Fix-up the ignores

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/fxpay#76]
Installing fxpay via bower gives this directory structure:

![1__vim](https://cloud.githubusercontent.com/assets/1514/6346981/15465348-bc0c-11e4-8baf-0c3f2027219f.png)

I think we can trim everything from this aside from the license and the min js file.

**Comment by kumar303** [comment]
I think including lib might be nice for when we support require JS (https://bugzilla.mozilla.org/show_bug.cgi?id=1121746) because projects such as Fireplace could work with individual unminified source files.
